# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gencode CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    
jobs:
  generate-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm link
    - run: npm link simplify-codegen
    - run: simplify-codegen template -i petsample
    - run: sed -i '/^x-deployment-name/s/:.*$/:\ test-pets-demo/' openapi.yaml
    - run: simplify-codegen generate -i openapi.yaml -p ${{ secrets.PROJECT_ID }} -a ${{ secrets.AWS_ACCOUNT_ID }} -o $PWD/ci-test
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "ci-test/test-pets-demo.json, ci-test/test-pets-demo.yaml, ci-test/policy-deployment.json, ci-test/policy-execute-api.json, ci-test/.env"
    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo All files exists!